# # Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# terraform {
#   backend "s3" {
#     bucket  = "riassume-terraform-state"
#     key     = "riassume/cdn/terraform.tfstate"
#     profile = "riassume"
#     region  = "us-east-1"
#   }
# }
