# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "us-east-1"
  profile = "work_us"
  default_tags {
    tags = {
      PROJECT   = "POC"
      Terraform = "true"
    }
  }
}
